// <auto-generated />
using System;
using DiscordBotSample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiscordBotSample.Data.Migrations
{
    [DbContext(typeof(LunchBotDbContext))]
    partial class LunchBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("DiscordBotSample.Entities.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("NextLocationLocationId");

                    b.Property<DateTime>("NextTime");

                    b.Property<string>("Version");

                    b.Property<int?>("WhoPaysPersonId");

                    b.HasKey("ApplicationId");

                    b.HasIndex("NextLocationLocationId");

                    b.HasIndex("WhoPaysPersonId");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("DiscordBotSample.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DiscordBotSample.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("DiscordBotSample.Entities.Application", b =>
                {
                    b.HasOne("DiscordBotSample.Entities.Location", "NextLocation")
                        .WithMany()
                        .HasForeignKey("NextLocationLocationId");

                    b.HasOne("DiscordBotSample.Entities.Person", "WhoPays")
                        .WithMany()
                        .HasForeignKey("WhoPaysPersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
